# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectionGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectionWindow(object):
    def setupUi(self, ConnectionWindow):
        ConnectionWindow.setObjectName("ConnectionWindow")
        ConnectionWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(ConnectionWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 40, 641, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.iPAddressLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.iPAddressLabel.setFont(font)
        self.iPAddressLabel.setObjectName("iPAddressLabel")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.iPAddressLabel)
        self.ipAddressLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ipAddressLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.ipAddressLineEdit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ipAddressLineEdit.setFont(font)
        self.ipAddressLineEdit.setObjectName("ipAddressLineEdit")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.ipAddressLineEdit)
        self.portLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.portLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.portLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.portLineEdit.setFont(font)
        self.portLineEdit.setObjectName("portLineEdit")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.portLineEdit)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(80, 250, 641, 121))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFormAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(30)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nickNameLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nickNameLabel.setFont(font)
        self.nickNameLabel.setObjectName("nickNameLabel")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.nickNameLabel)
        self.nickNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nickNameLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nickNameLineEdit.setFont(font)
        self.nickNameLineEdit.setObjectName("nickNameLineEdit")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.nickNameLineEdit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(
            QtCore.QRect(460, 390, 261, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connectButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.connectButton.setMinimumSize(QtCore.QSize(120, 35))
        self.connectButton.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.connectButton.setFont(font)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_2.addWidget(
            self.connectButton, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(
            self.cancelButton, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        ConnectionWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConnectionWindow)
        QtCore.QMetaObject.connectSlotsByName(ConnectionWindow)

    def retranslateUi(self, ConnectionWindow):
        _translate = QtCore.QCoreApplication.translate
        ConnectionWindow.setWindowTitle(_translate(
            "ConnectionWindow", "ConnectionWindow"))
        self.iPAddressLabel.setText(
            _translate("ConnectionWindow", "IP Address"))
        self.portLabel.setText(_translate("ConnectionWindow", "Port"))
        self.nickNameLabel.setText(_translate("ConnectionWindow", "Nick Name"))
        self.connectButton.setText(_translate("ConnectionWindow", "Connect"))
        self.cancelButton.setText(_translate("ConnectionWindow", "Cancel"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     ConnectionWindow = QtWidgets.QMainWindow()
#     ui = Ui_ConnectionWindow()
#     ui.setupUi(ConnectionWindow)
#     ConnectionWindow.show()
#     sys.exit(app.exec_())
