# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'groupChatGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_groupChat(object):
    def setupUi(self, groupChat):
        groupChat.setObjectName("groupChat")
        groupChat.resize(625, 496)
        self.sendButton_2 = QtWidgets.QPushButton(groupChat)
        self.sendButton_2.setGeometry(QtCore.QRect(300, 330, 161, 71))
        self.sendButton_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendButton_2.setFont(font)
        self.sendButton_2.setObjectName("sendButton_2")
        self.closeButton_2 = QtWidgets.QPushButton(groupChat)
        self.closeButton_2.setGeometry(QtCore.QRect(20, 420, 441, 40))
        self.closeButton_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.closeButton_2.setFont(font)
        self.closeButton_2.setObjectName("closeButton_2")
        self.groupMessageEdit = QtWidgets.QLineEdit(groupChat)
        self.groupMessageEdit.setGeometry(QtCore.QRect(20, 330, 271, 71))
        self.groupMessageEdit.setObjectName("groupMessageEdit")
        self.sendButton_3 = QtWidgets.QPushButton(groupChat)
        self.sendButton_3.setGeometry(QtCore.QRect(480, 420, 141, 41))
        self.sendButton_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendButton_3.setFont(font)
        self.sendButton_3.setObjectName("sendButton_3")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(groupChat)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 20, 431, 261))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.chatTitle = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chatTitle.setFont(font)
        self.chatTitle.setObjectName("chatTitle")
        self.verticalLayout_5.addWidget(
            self.chatTitle, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.verticalLayoutWidget_5)
        self.scrollArea_4.setMinimumSize(QtCore.QSize(429, 228))
        self.scrollArea_4.setMaximumSize(QtCore.QSize(16777215, 228))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.messagesScroll_2 = QtWidgets.QWidget()
        self.messagesScroll_2.setGeometry(QtCore.QRect(0, 0, 427, 226))
        self.messagesScroll_2.setMinimumSize(QtCore.QSize(410, 100))
        self.messagesScroll_2.setMaximumSize(QtCore.QSize(16777215, 416))
        self.messagesScroll_2.setObjectName("messagesScroll_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.messagesScroll_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 431, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.messagesScrollLayoutGroup = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_2)
        self.messagesScrollLayoutGroup.setContentsMargins(0, 0, 0, 0)
        self.messagesScrollLayoutGroup.setObjectName(
            "messagesScrollLayoutGroup")
        self.scrollArea_4.setWidget(self.messagesScroll_2)
        self.verticalLayout_5.addWidget(self.scrollArea_4)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(groupChat)
        self.verticalLayoutWidget_6.setGeometry(
            QtCore.QRect(470, 20, 141, 371))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.chatTitle_2 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chatTitle_2.setFont(font)
        self.chatTitle_2.setObjectName("chatTitle_2")
        self.verticalLayout_6.addWidget(self.chatTitle_2)
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_6)
        self.scrollArea.setMinimumSize(QtCore.QSize(139, 338))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.membersListScroll = QtWidgets.QWidget()
        self.membersListScroll.setGeometry(QtCore.QRect(0, 0, 137, 336))
        self.membersListScroll.setObjectName("membersListScroll")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.membersListScroll)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 141, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.membersListLayout = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget)
        self.membersListLayout.setContentsMargins(0, 0, 0, 0)
        self.membersListLayout.setObjectName("membersListLayout")
        self.scrollArea.setWidget(self.membersListScroll)
        self.verticalLayout_6.addWidget(self.scrollArea)

        self.retranslateUi(groupChat)
        QtCore.QMetaObject.connectSlotsByName(groupChat)

    def retranslateUi(self, groupChat):
        _translate = QtCore.QCoreApplication.translate
        groupChat.setWindowTitle(_translate("groupChat", "Group chat"))
        self.sendButton_2.setText(_translate("groupChat", "Send"))
        self.closeButton_2.setText(_translate("groupChat", "Close"))
        self.sendButton_3.setText(_translate("groupChat", "Invite"))
        self.chatTitle.setText(_translate("groupChat", "Room by"))
        self.chatTitle_2.setText(_translate("groupChat", "Members"))
