# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inviteGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inviteWindow(object):
    def setupUi(self, inviteWindow):
        inviteWindow.setObjectName("inviteWindow")
        inviteWindow.resize(244, 320)
        self.inviteButton = QtWidgets.QPushButton(inviteWindow)
        self.inviteButton.setGeometry(QtCore.QRect(20, 260, 101, 51))
        self.inviteButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inviteButton.setFont(font)
        self.inviteButton.setObjectName("inviteButton")
        self.closeButton = QtWidgets.QPushButton(inviteWindow)
        self.closeButton.setGeometry(QtCore.QRect(130, 260, 101, 51))
        self.closeButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(inviteWindow)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(20, 10, 211, 221))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.chatTitle_3 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chatTitle_3.setFont(font)
        self.chatTitle_3.setObjectName("chatTitle_3")
        self.verticalLayout_7.addWidget(self.chatTitle_3)
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_7)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.membersListScroll = QtWidgets.QWidget()
        self.membersListScroll.setGeometry(QtCore.QRect(0, 0, 207, 186))
        self.membersListScroll.setObjectName("membersListScroll")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.membersListScroll)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 211, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.inviteListLayout = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget)
        self.inviteListLayout.setContentsMargins(0, 0, 0, 0)
        self.inviteListLayout.setObjectName("inviteListLayout")
        self.scrollArea.setWidget(self.membersListScroll)
        self.verticalLayout_7.addWidget(self.scrollArea)

        self.retranslateUi(inviteWindow)
        QtCore.QMetaObject.connectSlotsByName(inviteWindow)

    def retranslateUi(self, inviteWindow):
        _translate = QtCore.QCoreApplication.translate
        inviteWindow.setWindowTitle(_translate("inviteWindow", "Invite"))
        self.inviteButton.setText(_translate("inviteWindow", "Invite"))
        self.closeButton.setText(_translate("inviteWindow", "Close"))
        self.chatTitle_3.setText(_translate("inviteWindow", "Members"))
