# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oneOnOneGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_oneOnOneWindow(object):
    def setupUi(self, oneOnOneWindow):
        oneOnOneWindow.setObjectName("oneOnOneWindow")
        oneOnOneWindow.resize(480, 643)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(oneOnOneWindow)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 50, 441, 431))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.singleChatListWidget = QtWidgets.QListWidget(
            self.verticalLayoutWidget_4)
        self.singleChatListWidget.setObjectName("singleChatListWidget")
        self.verticalLayout_4.addWidget(self.singleChatListWidget)
        self.closeButton = QtWidgets.QPushButton(oneOnOneWindow)
        self.closeButton.setGeometry(QtCore.QRect(20, 580, 441, 40))
        self.closeButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.oneOnOneMessageEdit = QtWidgets.QLineEdit(oneOnOneWindow)
        self.oneOnOneMessageEdit.setGeometry(QtCore.QRect(20, 490, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.oneOnOneMessageEdit.setFont(font)
        self.oneOnOneMessageEdit.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.oneOnOneMessageEdit.setObjectName("oneOnOneMessageEdit")
        self.sendButton = QtWidgets.QPushButton(oneOnOneWindow)
        self.sendButton.setGeometry(QtCore.QRect(300, 490, 161, 71))
        self.sendButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.chatTitle = QtWidgets.QLabel(oneOnOneWindow)
        self.chatTitle.setGeometry(QtCore.QRect(20, 20, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chatTitle.setFont(font)
        self.chatTitle.setObjectName("chatTitle")
        self.chatTitle.resize(300, 30)

        self.retranslateUi(oneOnOneWindow)
        QtCore.QMetaObject.connectSlotsByName(oneOnOneWindow)

    def retranslateUi(self, oneOnOneWindow):
        _translate = QtCore.QCoreApplication.translate
        oneOnOneWindow.setWindowTitle(
            _translate("oneOnOneWindow", "1:1 Window"))
        self.closeButton.setText(_translate("oneOnOneWindow", "Close"))
        self.sendButton.setText(_translate("oneOnOneWindow", "Send"))
        self.chatTitle.setText(_translate("oneOnOneWindow", "Chat with"))
