# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oneOnOneGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_oneOnOneWindow(object):
    def setupUi(self, oneOnOneWindow):
        oneOnOneWindow.setObjectName("oneOnOneWindow")
        oneOnOneWindow.resize(480, 643)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(oneOnOneWindow)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 441, 451))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chatTitle = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chatTitle.setFont(font)
        self.chatTitle.setObjectName("chatTitle")
        self.verticalLayout_4.addWidget(
            self.chatTitle, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.verticalLayoutWidget_4)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(100, 418))
        self.scrollArea_3.setMaximumSize(QtCore.QSize(16777215, 418))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.messagesScroll = QtWidgets.QWidget()
        self.messagesScroll.setGeometry(QtCore.QRect(0, 0, 437, 416))
        self.messagesScroll.setMinimumSize(QtCore.QSize(385, 416))
        self.messagesScroll.setMaximumSize(QtCore.QSize(16777215, 416))
        self.messagesScroll.setObjectName("messagesScroll")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.messagesScroll)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.messagesScrollLayout = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget)
        self.messagesScrollLayout.setContentsMargins(0, 0, 0, 0)
        self.messagesScrollLayout.setObjectName("messagesScrollLayout")
        self.scrollArea_3.setWidget(self.messagesScroll)
        self.verticalLayout_4.addWidget(self.scrollArea_3)
        self.closeButton = QtWidgets.QPushButton(oneOnOneWindow)
        self.closeButton.setGeometry(QtCore.QRect(20, 580, 441, 40))
        self.closeButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.oneOnOneMessageEdit = QtWidgets.QLineEdit(oneOnOneWindow)
        self.oneOnOneMessageEdit.setGeometry(QtCore.QRect(20, 490, 271, 71))
        self.oneOnOneMessageEdit.setObjectName("oneOnOneMessageEdit")
        self.sendButton = QtWidgets.QPushButton(oneOnOneWindow)
        self.sendButton.setGeometry(QtCore.QRect(300, 490, 161, 71))
        self.sendButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")

        self.retranslateUi(oneOnOneWindow)
        QtCore.QMetaObject.connectSlotsByName(oneOnOneWindow)

    def retranslateUi(self, oneOnOneWindow):
        _translate = QtCore.QCoreApplication.translate
        oneOnOneWindow.setWindowTitle(
            _translate("oneOnOneWindow", "1:1 Window"))
        self.chatTitle.setText(_translate("oneOnOneWindow", "Chat with"))
        self.closeButton.setText(_translate("oneOnOneWindow", "Close"))
        self.sendButton.setText(_translate("oneOnOneWindow", "Send"))
